# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  displayName: 'Visual Studio Build'
  inputs:
    solution: '**\*.sln'
    platform: 'x64'
    configuration: 'Release'
    maximumCpuCount: true
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install Latest VSTest'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
- task: VSTest@2
  displayName: 'Run VSTest'
  inputs:
    testSelector: 'testRun'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runTestsInIsolation: true